### ISSUE TITLE
Max CandleStick size?

### ISSUE THREAD

**Issue by Inseparable** [team172011/ta4jCharting#3]
Hey guys, thanks for that easy charting, but I get an error if i put a lot of data (1 week of 1 min candles) in the chart, I wonder whats the issue here? Im sure there are no duplicates, this seems to occour on sundays only 🤔

```
Exception in thread "main" org.jfree.data.general.SeriesException: You are attempting to add an observation for the time period Sun Oct 31 02:10:59 CET 2021 but the series already contains an observation for that time period. Duplicates are not permitted.  Try using the addOrUpdate() method.
	at org.jfree.data.time.TimeSeries.add(TimeSeries.java:701)
	at org.jfree.data.time.TimeSeries.add(TimeSeries.java:746)
	at org.jfree.data.time.TimeSeries.add(TimeSeries.java:732)
	at ta4jchart.converter.IndicatorConverterImpl.apply(IndicatorConverterImpl.java:22)
	at ta4jchart.converter.IndicatorConverterImpl.apply(IndicatorConverterImpl.java:1)
	at ta4jchart.chartbuilder.ChartBuilderImpl.addIndicator(ChartBuilderImpl.java:92)
```

**Comment by team172011** [comment]
Hi @Inseparable can you provide any working example for this issue?
